name: Publish package to GitHub Packages

# Only trigger, when the build workflow succeeded
#on:
#  workflow_run:
#    workflows: ["Java CI with Maven"]
#    types:
#      - completed
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Publish package
        run: mvn --batch-mode deploy -DdeploySnapshot=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
